### ISSUE TITLE
Fix Dates

### ISSUE THREAD

**Issue by jschulberg** [jschulberg/DC-Transportation-Crashes#4]
The dates are coming in as 12-digit numbers. I'm not so sure why or exactly how they should be formatted. Still investigating.

**Comment by Seahawks500** [comment]
I figured out the issue. All the dates have a +00 appended to the end. I'm going to edit the crashes_in_dc file and resave it.

**Comment by adampeir** [comment]
I added some code that converts the 12-digit timestamp encoding to datetime
